spring:
  application:
    name: "ms-ecommerce"
  datasource:
    url: "jdbc:h2:mem:ms-ecommerce-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
    username: "${MS_NAME:root}"
    password: "${FAMILY_POSTGRES_PASSWORD:root}"
    driverClassName: "org.h2.Driver"
    hikari:
      maximum-pool-size: "10"
      connection-timeout: "20000"
      minimum-idle: "1"
      idle-timeout: "300000"
      max-lifetime: "300000"
      leak-detection-threshold: "300000"
  jpa:
    database-platform: "org.hibernate.dialect.H2Dialect"
    generate-ddl: "false"
    show-sql: "true"
    hibernate:
      ddl-auto: "none"
    properties:
      hibernate:
        format_sql: "true"
        jdbc:
          time_zone: "${TIME_ZONE:UTC}"
        hbm2ddl:
          import_files: "schema.sql"
  h2:
    console:
      enabled: true
      path: /h2-db-console
      settings.trace: false
      settings.web-allow-others: false

server:
  port: "${SERVER_PORT:8080}"
  servlet:
    context-path: "${SERVLET_CONTEXT_PATH:/ecommerce/}"
  error:
    include-stacktrace: "ALWAYS"
    include-message: "ALWAYS"

management:
  endpoints:
    web:
      exposure:
        include: "*"
    loggers:
      enabled: true

logging:
  pattern:
    level: "%clr(%5p) %clr([TraceId=%X{traceId:-} B3SpanId=%X{spanId:-}]){green}"

